openapi: 3.0.0
info:
  title: Pixel Puurfect GPT API
  version: 1.0.0
servers:
  - url: 'https://pixel-puuurfect-gpt---2-9jr8qezw.uc.gateway.dev'
    description: Production server
paths:
  /:
    post:
      summary: Upload static site HTML
      description: Endpoint to upload index.html contents and associated files.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                index:
                  type: string
                  description: Contents of index.html.
                files:
                  type: object
                  additionalProperties:
                    type: string
                  description: Map of filenames to their contents.
      responses:
        '200':
          description: Upload successful
        '400':
          description: Invalid input
        '500':
          description: Server error

